import tkinter as tk
window = tk.Tk()
window.title("Login_Program ")
window.geometry("300x350")

# Tạo một frame (khung)
frame1 = tk.Frame(window, width=100, height=200, bg="lightgray", bd=5, relief="ridge").pack(padx=5, pady=5, fill="both", expand=True)
frame2 = tk.Frame(window, width=50, bg="lightgray", bd=5, relief="ridge").pack(padx=5, pady=5, fill="both", expand=True)
label_FN = tk.Label(frame1, text="First Name:", font=("Arial", 10)).place(x=10,y=20)
entry_FN=tk.Entry(frame1).place(x=150,y=20)
label_LN = tk.Label(frame1, text="Last Name:", font=("Arial", 10)).place(x=10,y=50)
entry_LN=tk.Entry(frame1).place(x=150,y=50)
label_ADDL1 = tk.Label(frame1, text="Address Line 1:", font=("Arial", 10)).place(x=10,y=80)
entry_ADDL1=tk.Entry(frame1).place(x=150,y=80)
label_ADDL2 = tk.Label(frame1, text="Address Line 2:", font=("Arial", 10)).place(x=10,y=110)
entry_ADDL2=tk.Entry(frame1).place(x=150,y=110)
label_city = tk.Label(frame1, text="City:", font=("Arial", 10)).place(x=10,y=140)
entry_city=tk.Entry(frame1).place(x=150,y=140)
label_sp = tk.Label(frame1, text="State/Province:", font=("Arial", 10)).place(x=10,y=170)
entry_sp=tk.Entry(frame1).place(x=150,y=170)
label_pc = tk.Label(frame1, text="Postal code:", font=("Arial", 10)).place(x=10,y=200)
entry_pc=tk.Entry(frame1).place(x=150,y=200)
label_ctry = tk.Label(frame1, text="country:", font=("Arial", 10)).place(x=10,y=230)
entry_ctry=tk.Entry(frame1).place(x=150,y=230)
btn_clear = tk.Button(frame2, text="Clear", bg="gray", fg="white").place(x=180,y=300)
btn_sub = tk.Button(frame2, text="Submit", bg="gray", fg="white").place(x=230,y=300)
window.mainloop()